version: "2"

services: 
  iot_http_server:
    build: .
    restart: unless-stopped
    environment: 
      - dbaddr=$dbaddr
      - dbport=$dbport
      - dbuser=$dbuser
      - dbpass=$dbpass
      - dbname=$dbname
      - secretkey=$secretkey
      - debug=$debug
      
    container_name: "iot_http_server"
    ports:
      - '8000:80'
