version: "2"

services: 
  mutech-iot-http-server:
    build: .
    restart: unless-stopped
    environment: 
      - dbaddr=$dbaddr
      - dbport=$dbport
      - dbuser=$dbuser
      - dbpass=$dbpass
      - dbname=$dbname
      - secretkey=$secretkey
      - debug=$debug
      
    container_name: "iot-http-server"
    ports:
      - '8000:80'
