version: "2"

services: 
  mutech-iot-http-server:
    build: .
    restart: unless-stopped
    environment: 
      - dbaddr=$dbaddr
      - dbport=$dbport
      - dbuser=$dbuser
      - dbpass=$dbpass
      - dbname=$dbname
      - secretkey=$secretkey
      - debug=$debug
      - email_host=$email_host
      - email_port=$email_port
      - email_address=$email_address
      - email_apikey=$email_apikey
      
    container_name: "iot-http-server"
    ports:
      - '8000:80'
