# Generated by Django 3.0.6 on 2020-05-14 16:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('mqtt_client_id', models.UUIDField(default=uuid.uuid4)),
            ],
            options={
                'verbose_name_plural': 'Devices',
                'db_table': 'Devices',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('mqtt_username', models.UUIDField(default=uuid.uuid4)),
                ('mqtt_password', models.UUIDField(default=uuid.uuid4)),
            ],
            options={
                'verbose_name_plural': 'Users',
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Device')),
            ],
            options={
                'verbose_name_plural': 'States',
                'db_table': 'States',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Device')),
            ],
            options={
                'verbose_name_plural': 'Data',
                'db_table': 'Data',
            },
        ),
    ]
