# Generated by Django 3.0.7 on 2020-06-21 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='device',
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
