# Generated by Django 3.0.7 on 2020-07-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_remove_data_serialized'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='serialized',
            field=models.TextField(default=None),
        ),
    ]
