# Generated by Django 3.0.7 on 2020-07-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_data_serialized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='serialized',
            field=models.TextField(default=''),
        ),
    ]
