# Generated by Django 3.0.7 on 2020-07-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20200703_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='serialized',
            field=models.TextField(default=None, null=True),
        ),
    ]
