# Generated by Django 3.0.7 on 2020-07-03 21:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20200703_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='serialized',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
